name: Build app and deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: use Node.js 13.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build:prod
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          SOURCE: "./build"
          REMOTE_HOST: "118.190.37.169"
          # 用户
          REMOTE_USER: "root"
          TARGET: "/root/web/anthhub/deploy/react-mini-blog"
